# Generated by Django 4.2.1 on 2023-05-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='type',
        ),
    ]
