# Generated by Django 4.2.1 on 2023-06-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify', '0002_alter_category_type_alter_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
