# Generated by Django 4.2.1 on 2023-05-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify', '0003_events_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.CharField(choices=[('P', 'Party'), ('E', 'Event'), ('S', 'Show')], default='Event', max_length=60),
        ),
    ]
