# Generated by Django 4.2.1 on 2023-06-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify', '0003_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start', '-end']},
        ),
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(default=None, upload_to='banner'),
        ),
    ]
