# Generated by Django 4.2.1 on 2023-06-05 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify', '0004_alter_categories_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Party'), ('E', 'Event'), ('S', 'Show'), ('B', 'Bonfire')], default='Event', max_length=60)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('P', 'Party'), ('E', 'Event'), ('S', 'Show'), ('B', 'Bonfire')], default='Event', max_length=60)),
                ('location', models.CharField(max_length=200)),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payments',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='event_id',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.AddField(
            model_name='category',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventify.event'),
        ),
    ]
