# Generated by Django 4.2.1 on 2023-06-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify', '0004_alter_event_options'),
    ]

    operations = [
        
    ]
