# Generated by Django 4.2.1 on 2023-06-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify', '0005_category_event_remove_payments_ticket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(default=None, upload_to='banner'),
        ),
    ]
