# Generated by Django 4.2.1 on 2023-06-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify', '0005_category_event_remove_payments_ticket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('C', 'Concert'), ('C', 'Communities'), ('C', 'Classes'), ('P', 'Parties'), ('S', 'Sport')], default='Event', max_length=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('C', 'Concert'), ('C', 'Communities'), ('C', 'Classes'), ('P', 'Parties'), ('S', 'Sport')], default='Event', max_length=60),
        ),
    ]
