# Generated by Django 4.2.1 on 2023-06-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventify', '0007_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
